[package]
name = "total5"
version = "0.1.0"
edition = "2021"
description = "A Rust implementation of the Total.js v5 web framework"
license = "MIT"

[dependencies]
async-trait = "0.1.80"
base64 = "0.22"
bytes = "1.6.0"
chrono = { version = "=0.4.38", features = ["serde"] }
flate2 = "1.0"
http = "1.1.0"
hmac = "0.12"
once_cell = "1.19.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
sha2 = "0.10"
rustls = "0.22"
rustls-pemfile = "2.1"
postgres-protocol = { version = "=0.6.6", optional = true }
postgres-types = { version = "=0.2.6", optional = true }
tokio-postgres = { version = "=0.7.10", features = ["with-serde_json-1"], optional = true }
tokio = { version = "1.38.0", features = ["full"] }
tokio-rustls = "0.25"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
uuid = { version = "=1.10.0", features = ["v4"] }
webpki-roots = "0.26"
zeroize = "=1.7.0"

[dev-dependencies]
rcgen = "0.12"
time = "=0.3.36"

[features]
build = []
postgres = ["dep:tokio-postgres", "dep:postgres-protocol", "dep:postgres-types"]
