[package]
name = "framework-test"
version = "0.1.0"
edition = "2021"
description = "Test application for the framework library"

[dependencies]
lazy_static = "1.5.0"
serde_json = "1.0.140"
total5 = { path = "../" }  # Reference the framework library in the parent directory
